### ISSUE TITLE
Wrong/Outdated instructions

### ISSUE THREAD

**Issue by gitcnd** [alecGraves/Fusion360PrinterMaterials#2]
"In Fusion360, go to MODIFY ..."  there is no such thing.

The correct instructions are:  

- Click the UTILITIES Tab, 
- then the "UTILITY" drop-down menu, 
- then the first option "Manage Materials", 
- then click to expand the bottom-left icon of a folder 
- and pick the "Open Existing Library" option.

**Comment by gitcnd** [comment]
![Screen Shot 2022-04-10 at 7 12 15 pm](https://user-images.githubusercontent.com/4301826/162611452-deecd524-123c-48cc-83ad-b3f8d42b2060.png)

**Comment by alecGraves** [comment]
Thank you for making these up-to-date instructions! I will update the current usage instructions in the README.
