### ISSUE TITLE
Material Request, ASA

### ISSUE THREAD

**Issue by maxall41** [alecGraves/Fusion360PrinterMaterials#4]
Could ASA be added to this library? I often prefer using it over ABS because of it's UV resistance properties.

**Comment by alecGraves** [comment]
Yeah, this would be good to add. My team also has ended up using ASA much more due to its weather resistance.

**Comment by alecGraves** [comment]
I have added ASA based (mostly) on PolyMaker "PolyLite ASA" data: https://us.polymaker.com/products/polylite-asa
